// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: notice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NoticeServiceClient is the client API for NoticeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoticeServiceClient interface {
	CreateNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error)
	ShowNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeDetailReply, error)
	ShowAllNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeDetailReply, error)
	UpdateNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error)
	DeleteNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error)
}

type noticeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoticeServiceClient(cc grpc.ClientConnInterface) NoticeServiceClient {
	return &noticeServiceClient{cc}
}

func (c *noticeServiceClient) CreateNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error) {
	out := new(NoticeReply)
	err := c.cc.Invoke(ctx, "/NoticeService/CreateNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) ShowNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeDetailReply, error) {
	out := new(NoticeDetailReply)
	err := c.cc.Invoke(ctx, "/NoticeService/ShowNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) ShowAllNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeDetailReply, error) {
	out := new(NoticeDetailReply)
	err := c.cc.Invoke(ctx, "/NoticeService/ShowAllNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) UpdateNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error) {
	out := new(NoticeReply)
	err := c.cc.Invoke(ctx, "/NoticeService/UpdateNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) DeleteNotice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error) {
	out := new(NoticeReply)
	err := c.cc.Invoke(ctx, "/NoticeService/DeleteNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoticeServiceServer is the server API for NoticeService service.
// All implementations must embed UnimplementedNoticeServiceServer
// for forward compatibility
type NoticeServiceServer interface {
	CreateNotice(context.Context, *NoticeRequest) (*NoticeReply, error)
	ShowNotice(context.Context, *NoticeRequest) (*NoticeDetailReply, error)
	ShowAllNotice(context.Context, *NoticeRequest) (*NoticeDetailReply, error)
	UpdateNotice(context.Context, *NoticeRequest) (*NoticeReply, error)
	DeleteNotice(context.Context, *NoticeRequest) (*NoticeReply, error)
	mustEmbedUnimplementedNoticeServiceServer()
}

// UnimplementedNoticeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNoticeServiceServer struct {
}

func (UnimplementedNoticeServiceServer) CreateNotice(context.Context, *NoticeRequest) (*NoticeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotice not implemented")
}
func (UnimplementedNoticeServiceServer) ShowNotice(context.Context, *NoticeRequest) (*NoticeDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowNotice not implemented")
}
func (UnimplementedNoticeServiceServer) ShowAllNotice(context.Context, *NoticeRequest) (*NoticeDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAllNotice not implemented")
}
func (UnimplementedNoticeServiceServer) UpdateNotice(context.Context, *NoticeRequest) (*NoticeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotice not implemented")
}
func (UnimplementedNoticeServiceServer) DeleteNotice(context.Context, *NoticeRequest) (*NoticeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNotice not implemented")
}
func (UnimplementedNoticeServiceServer) mustEmbedUnimplementedNoticeServiceServer() {}

// UnsafeNoticeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoticeServiceServer will
// result in compilation errors.
type UnsafeNoticeServiceServer interface {
	mustEmbedUnimplementedNoticeServiceServer()
}

func RegisterNoticeServiceServer(s grpc.ServiceRegistrar, srv NoticeServiceServer) {
	s.RegisterService(&NoticeService_ServiceDesc, srv)
}

func _NoticeService_CreateNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).CreateNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoticeService/CreateNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).CreateNotice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_ShowNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).ShowNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoticeService/ShowNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).ShowNotice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_ShowAllNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).ShowAllNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoticeService/ShowAllNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).ShowAllNotice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_UpdateNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).UpdateNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoticeService/UpdateNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).UpdateNotice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_DeleteNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).DeleteNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoticeService/DeleteNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).DeleteNotice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoticeService_ServiceDesc is the grpc.ServiceDesc for NoticeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoticeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NoticeService",
	HandlerType: (*NoticeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNotice",
			Handler:    _NoticeService_CreateNotice_Handler,
		},
		{
			MethodName: "ShowNotice",
			Handler:    _NoticeService_ShowNotice_Handler,
		},
		{
			MethodName: "ShowAllNotice",
			Handler:    _NoticeService_ShowAllNotice_Handler,
		},
		{
			MethodName: "UpdateNotice",
			Handler:    _NoticeService_UpdateNotice_Handler,
		},
		{
			MethodName: "DeleteNotice",
			Handler:    _NoticeService_DeleteNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notice.proto",
}
