// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"mission/task5/hertz/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {

	// http://localhost:8888/createuser/zhangsan/zhangsan@email.com
	// http://localhost:8888/createuser/lisi/lisi@email.com
	// http://localhost:8888/updateuserbyname/zhangsan/zs@email.com
	// http://localhost:8888/deleteuserbyname/zhangsan
	r.GET("/createuser/:name/:email", handler.CreateUser)
	r.GET("/updateuserbyname/:name/:email", handler.UpdateUserByName)
	r.GET("/deleteuserbyname/:name", handler.DeleteUserByName)

	r.POST("/createnotice/", handler.CreateNotice)
	r.GET("/shownotice/:id", handler.ShowNotice)
	r.GET("/showallnotice/", handler.ShowAllNotice)
	r.POST("/updatenotice/", handler.UpdateNotice)
	r.GET("/deletenotice/:id", handler.DeleteNotice)

}
