// Code generated by hertz generator.
package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "mission/task4/hertz/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	//r.GET("/ping", handler.Ping)

	// your code ...
	// http://localhost:8888/createuser/zhangsan/zhangsan@email.com
	// http://localhost:8888/createuser/lisi/lisi@email.com
	r.GET("/createuser/:name/:email", handler.CreateUser)
	// http://localhost:8888/getuserbyname/zhangsan
	r.GET("/getuserbyname/:name", handler.GetUserByName)
	// http://localhost:8888/getalluser
	r.GET("/getalluser", handler.GetAllUser)
	// http://localhost:8888/updateuserbyname/zhangsan/zs@email.com
	r.GET("/updateuserbyname/:name/:email", handler.UpdateUserByName)
	// http://localhost:8888/deleteuserbyname/zhangsan
	r.GET("/deleteuserbyname/:name", handler.DeleteUserByName)

}
